version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run -v $(pwd):/usr/share/nginx/html:ro -d nginx
      - run: curl 127.0.0.1 | grep "Do it" || exit 1
      - run: 
          command: mkdir artifacts && mv index.html artifacts/
          when: always
      - store_artifacts:
          path: artifacts